name = "edge-api"
main = "src/index.ts"
compatibility_date = "2023-10-30"

[[d1_databases]]
binding = "DB"
database_name = "store-platform-db"
database_id = "fa079adc-06d5-427b-9721-9b151d0b9299"

[vars]
STRIPE_SECRET_KEY = "sk_test_51SG4XIL7PBahJaB0FCnX5MLD78S87KF74LSMXm6lPldgcCGsSnOdurfZTKe8CimZzUqzpAY6zezeJSIsfMZSB52i00A8tLwnEg"
STRIPE_WEBHOOK_SECRET = "whsec_..."
ADMIN_API_KEY = "admin-secret-key"
